





























}    return (0);    // ...existing code...    }        exit(1);        free_map(&game);        // Clean up and exit        ft_printf("Error\nMap must be surrounded by walls!\n");    {    if (!check_map_walls(game.map, &game))    }        return (1);        ft_printf("Error\nFailed to initialize game!\n");    {    if (!init_game(&game, argv[1]))    }        return (1);        ft_printf("Usage: %s <map_file>\n", argv[0]);    {    if (argc != 2)    t_game game;{int main(int argc, char **argv)#include "so_long.h"