





























































#endifint		ft_check_map_walls(char **map, t_game *game);int		ft_check_map(t_game *game);int		ft_check_map_validity(t_game *game);int		ft_check_map_path(t_game *game);int		ft_check_map_borders(t_game *game);int		ft_check_map_chars(t_game *game);int		ft_check_map_size(t_game *game);int		ft_check_walls(t_game *game);int		ft_check_collectibles(t_game *game);int		ft_check_exit(t_game *game, int x, int y);int		ft_collect(t_game *game, int x, int y);int		ft_move_player(t_game *game, int x, int y);int		ft_draw_map(t_game *game);int		ft_load_images(t_game *game);int		ft_render(t_game *game);int		ft_check_map(t_game *game);int		ft_read_map(char *file, t_game *game);int		ft_exit(t_game *game);int		ft_key_press(int keycode, t_game *game);int		ft_close(t_game *game);}				t_game;	int		moves;	int		collectibles;	int		player_y;	int		player_x;	int		map_height;	int		map_width;	char	**map;	t_img	img;	void	*win;	void	*mlx;{typedef struct s_game}				t_img;	int		height;	int		width;	void	*img;{typedef struct s_img# define KEY_D 2# define KEY_S 1# define KEY_A 0# define KEY_W 13# define KEY_ESC 53# define X_EVENT_KEY_EXIT 17# define X_EVENT_KEY_PRESS 2# define BUFFER_SIZE 1# include "libft.h"# include <mlx.h># include <stdio.h># include <fcntl.h># include <unistd.h># include <stdlib.h># define SO_LONG_H#ifndef SO_LONG_H